org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# https://github.com/neoforged/ModDevGradle?tab=readme-ov-file#better-minecraft-parameter-names--javadoc-parchment
# https://parchmentmc.org/docs/getting-started
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.197
neo_version_range=[21.1.197,)
loader_version_range=[1,)

mod_id=jojo_ripples
file_name=RipplesOfThePast-NeoForge
mod_version=0.4
snapshot_version=260111-a
release_snapshot=true
mod_group_id=standobyte.jojo

# FML
# systemProp.https.proxyHost=127.0.0.1
# systemProp.https.proxyPort=10808
